[package]
name = "excel2pg"
version = "0.1.0"
authors = ["Anton Rechenauer <antonrechenauer@gmail.com>"]
edition = "2018"

[dependencies]
calamine = "0.15.3"
diesel = { version = "1.0.0", features=["postgres","chrono"] }
dotenv = "0.9.0"
walkdir = "2"
chrono = "0.4.6"